#!/bin/bash
######################################################################
# process-replaygain
# 
# Usage:
#     process-replaygain DIRECTORY OPTS
######################################################################
date=$(eval date +%Y%m%d)
workingDir=""
scriptsDir=$HOME/code/scripts
logFile=$scriptsDir/logs/mp3gain-$date.tsv
errLogFile=$scriptsDir/logs/mp3gain-$date.err.log
mp3gainOpts="-T -k -o "
mp3NamePattern="*.mp3"
findOpts="-type d -print0"
while [[ $# > 0 ]]
do
  arg="$1"
  if [[ -d $arg ]]
  then
    workingDir="$(readlink -f $arg)"
  else
    mp3gainOpts=$mp3gainOpts$arg
  fi
  shift
done
if ! [[ $mp3gainOpts =~ .*(-a|-r).* ]]
then
  echo "Missing required option. Please specify -a or -r."
  exit 1
elif [[ $mp3gainOpts =~ .*-a.* ]] && [[ $mp3gainOpts =~ .*-r.* ]]
then
  echo "Invalid options. Please specify -a or -r (not both)."
  exit 1
fi
if [[ $workingDir == "" ]]
then
  echo "Please specify a directory for processing."
  exit 1
fi

process_dir() {
  echo "Processing replaygain for mp3 files in "$@""
  cd "$@"
  if ls $mp3NamePattern 1> /dev/null 2>&1; then
    mp3gain $mp3gainOpts $mp3NamePattern >> $logFile 2>> $errLogFile
  else
    echo "No matching files in this directory."
  fi
}
if [[ $mp3gainOpts =~ .*-a.* ]]
then
  echo "Using album mode for each subdirectory of $workingDir"
  find $workingDir/* $findOpts | while read -d $'\0' -r dir
  do
    process_dir "$dir"
  done
else
  echo "Using track mode for all tracks in $workingDir"
  process_dir "$workingDir"
fi
